#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/mnt/nfs/bin:/mnt/nfs/sbin:/mnt/nfs/usr/bin:/mnt/nfs/usr/sbin
export LD_LIBRARY_PATH=/mnt/nfs/lib:/mnt/nfs/usr/lib
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export PS1='\u@\h:\w\$ '

alias pactl="env HOME=/tmp pactl"

export GST_PLUGIN_PATH=/usr/lib/gstreamer-0.10
export GST_REGISTRY_UPDATE=1
export GST_REGISTRY=/mnt/nfs/gst-reg.bin

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -z /bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
